// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASTA9M07NXtboohmRhILwXvqDiPeDYdII',
    appId: '1:942275160903:web:0c8e5a95c0ac354a7e7a62',
    messagingSenderId: '942275160903',
    projectId: 'th4flutter',
    authDomain: 'th4flutter.firebaseapp.com',
    storageBucket: 'th4flutter.firebasestorage.app',
    measurementId: 'G-GB1P29Y5S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA77evo8mWL6XDJ9lgHJ1WJ-mUUyoBqT44',
    appId: '1:942275160903:android:41506adaf93430607e7a62',
    messagingSenderId: '942275160903',
    projectId: 'th4flutter',
    storageBucket: 'th4flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDadR9gISWNUIDO2gjFfsqhKKQBIezrQZc',
    appId: '1:942275160903:ios:2b9fc4c2b7ea43027e7a62',
    messagingSenderId: '942275160903',
    projectId: 'th4flutter',
    storageBucket: 'th4flutter.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDadR9gISWNUIDO2gjFfsqhKKQBIezrQZc',
    appId: '1:942275160903:ios:2b9fc4c2b7ea43027e7a62',
    messagingSenderId: '942275160903',
    projectId: 'th4flutter',
    storageBucket: 'th4flutter.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASTA9M07NXtboohmRhILwXvqDiPeDYdII',
    appId: '1:942275160903:web:9c492810d55a38437e7a62',
    messagingSenderId: '942275160903',
    projectId: 'th4flutter',
    authDomain: 'th4flutter.firebaseapp.com',
    storageBucket: 'th4flutter.firebasestorage.app',
    measurementId: 'G-7Y02CV3SNH',
  );

}